from faker import Faker
from pprint import pprint

f = Faker(locale='en_US')


def create_fake_person_data():
    content = []
    for i in range(100):
        first_name = f.first_name()
        index = i % 3
        mail_list = [f.email(), f.company_email(), f.ascii_company_email()]
        email = mail_list[index]
        if i % 9 == 0:
            email = first_name + "@163.com"
        content.append({
            "no": str(i),
            "first_name": first_name,
            "last_name": f.last_name(),
            "phone": f.phone_number(),
            "email": email,
            "zipcode": f.zipcode(),
            "birthday": f.date_of_birth(),
            "state": f.state()
        })

    pprint(content)
    return content


import datetime

user_data = [{'birthday': datetime.date(1960, 1, 30),
              'email': 'Joseph@163.com',
              'first_name': 'Joseph',
              'last_name': 'Reyes',
              'no': '0',
              'phone': '+1-014-121-4564x406',
              'state': 'Mississippi',
              'zipcode': '66915'},
             {'birthday': datetime.date(1922, 8, 21),
              'email': 'martinezgregory@johnson.com',
              'first_name': 'Joshua',
              'last_name': 'Robertson',
              'no': '1',
              'phone': '001-327-776-4183x9140',
              'state': 'Idaho',
              'zipcode': '50657'},
             {'birthday': datetime.date(1957, 2, 4),
              'email': 'vickie31@bradley.com',
              'first_name': 'Kristin',
              'last_name': 'White',
              'no': '2',
              'phone': '117.457.2749x82039',
              'state': 'Missouri',
              'zipcode': '98069'},
             {'birthday': datetime.date(1948, 5, 7),
              'email': 'iluna@pineda.com',
              'first_name': 'Michael',
              'last_name': 'Duke',
              'no': '3',
              'phone': '001-409-300-2175x0183',
              'state': 'Mississippi',
              'zipcode': '53174'},
             {'birthday': datetime.date(1910, 5, 23),
              'email': 'philip49@mendez.biz',
              'first_name': 'Adam',
              'last_name': 'Marshall',
              'no': '4',
              'phone': '(316)784-9635',
              'state': 'Alaska',
              'zipcode': '87164'},
             {'birthday': datetime.date(1980, 1, 27),
              'email': 'mariageorge@ochoa-brown.org',
              'first_name': 'Daniel',
              'last_name': 'Trevino',
              'no': '5',
              'phone': '693-580-1894x534',
              'state': 'Delaware',
              'zipcode': '66787'},
             {'birthday': datetime.date(2015, 3, 28),
              'email': 'murphytara@yahoo.com',
              'first_name': 'Ryan',
              'last_name': 'Ramirez',
              'no': '6',
              'phone': '(443)484-6161x4270',
              'state': 'Utah',
              'zipcode': '58348'},
             {'birthday': datetime.date(1991, 3, 13),
              'email': 'gmorton@williams-lopez.com',
              'first_name': 'Kendra',
              'last_name': 'Perez',
              'no': '7',
              'phone': '456-060-3999x6224',
              'state': 'New York',
              'zipcode': '78797'},
             {'birthday': datetime.date(1982, 3, 25),
              'email': 'zsilva@underwood-alvarez.biz',
              'first_name': 'Daniel',
              'last_name': 'Walker',
              'no': '8',
              'phone': '626-164-8959x496',
              'state': 'Washington',
              'zipcode': '91326'},
             {'birthday': datetime.date(1951, 5, 1),
              'email': 'Hannah@163.com',
              'first_name': 'Hannah',
              'last_name': 'Williams',
              'no': '9',
              'phone': '001-455-457-2602x68323',
              'state': 'South Carolina',
              'zipcode': '80939'},
             {'birthday': datetime.date(1929, 6, 24),
              'email': 'murphyedwin@franklin-rodriguez.com',
              'first_name': 'Tara',
              'last_name': 'Murphy',
              'no': '10',
              'phone': '+1-551-000-4020',
              'state': 'Alaska',
              'zipcode': '11138'},
             {'birthday': datetime.date(1910, 10, 16),
              'email': 'xmurray@ford.com',
              'first_name': 'John',
              'last_name': 'Porter',
              'no': '11',
              'phone': '+1-873-785-2393x78162',
              'state': 'Colorado',
              'zipcode': '78199'},
             {'birthday': datetime.date(1979, 7, 14),
              'email': 'anthony71@hotmail.com',
              'first_name': 'Brett',
              'last_name': 'Reynolds',
              'no': '12',
              'phone': '522-826-8703',
              'state': 'Nebraska',
              'zipcode': '45425'},
             {'birthday': datetime.date(1995, 10, 24),
              'email': 'wayne73@harris-james.com',
              'first_name': 'Bianca',
              'last_name': 'Roy',
              'no': '13',
              'phone': '726-917-6544',
              'state': 'Connecticut',
              'zipcode': '12964'},
             {'birthday': datetime.date(1938, 4, 4),
              'email': 'olivercarol@molina.net',
              'first_name': 'Alejandro',
              'last_name': 'Moreno',
              'no': '14',
              'phone': '+1-796-135-5551x258',
              'state': 'Kansas',
              'zipcode': '17011'},
             {'birthday': datetime.date(1946, 9, 17),
              'email': 'pknapp@gmail.com',
              'first_name': 'Chad',
              'last_name': 'White',
              'no': '15',
              'phone': '001-325-954-0946x640',
              'state': 'South Carolina',
              'zipcode': '32966'},
             {'birthday': datetime.date(1950, 10, 20),
              'email': 'rebeccacohen@johnston.net',
              'first_name': 'Danielle',
              'last_name': 'Jackson',
              'no': '16',
              'phone': '001-137-974-3686x272',
              'state': 'Nebraska',
              'zipcode': '49027'},
             {'birthday': datetime.date(1943, 4, 7),
              'email': 'kelly60@brown.com',
              'first_name': 'Jacob',
              'last_name': 'Clayton',
              'no': '17',
              'phone': '(191)698-1938',
              'state': 'New Hampshire',
              'zipcode': '04701'},
             {'birthday': datetime.date(1940, 6, 12),
              'email': 'Jeremy@163.com',
              'first_name': 'Jeremy',
              'last_name': 'West',
              'no': '18',
              'phone': '398.026.3598x445',
              'state': 'New Mexico',
              'zipcode': '80262'},
             {'birthday': datetime.date(1988, 4, 27),
              'email': 'edwardmueller@casey.biz',
              'first_name': 'Monica',
              'last_name': 'Johnson',
              'no': '19',
              'phone': '585-401-3929x32162',
              'state': 'Michigan',
              'zipcode': '62420'},
             {'birthday': datetime.date(1913, 12, 24),
              'email': 'holson@grant-macdonald.net',
              'first_name': 'Anthony',
              'last_name': 'Nash',
              'no': '20',
              'phone': '9385414964',
              'state': 'Virginia',
              'zipcode': '06222'},
             {'birthday': datetime.date(2007, 5, 5),
              'email': 'burkechristy@yahoo.com',
              'first_name': 'Lauren',
              'last_name': 'Booth',
              'no': '21',
              'phone': '(098)050-5008',
              'state': 'Montana',
              'zipcode': '91898'},
             {'birthday': datetime.date(2001, 4, 12),
              'email': 'pgarcia@bailey.com',
              'first_name': 'Brandi',
              'last_name': 'Pierce',
              'no': '22',
              'phone': '028-363-8740x0833',
              'state': 'Colorado',
              'zipcode': '06361'},
             {'birthday': datetime.date(2014, 3, 26),
              'email': 'robertcunningham@morrow.org',
              'first_name': 'Derek',
              'last_name': 'Reed',
              'no': '23',
              'phone': '001-841-830-9764x71072',
              'state': 'Massachusetts',
              'zipcode': '63070'},
             {'birthday': datetime.date(1968, 10, 4),
              'email': 'petersenjonathan@hotmail.com',
              'first_name': 'Brandon',
              'last_name': 'Holloway',
              'no': '24',
              'phone': '(791)733-1066x1729',
              'state': 'Maine',
              'zipcode': '41378'},
             {'birthday': datetime.date(1992, 5, 30),
              'email': 'dhouston@green.com',
              'first_name': 'Travis',
              'last_name': 'Turner',
              'no': '25',
              'phone': '311.586.7329',
              'state': 'Ohio',
              'zipcode': '44886'},
             {'birthday': datetime.date(1905, 3, 25),
              'email': 'heather98@peterson.com',
              'first_name': 'Danielle',
              'last_name': 'Hicks',
              'no': '26',
              'phone': '619.819.0834',
              'state': 'Ohio',
              'zipcode': '68194'},
             {'birthday': datetime.date(2010, 4, 24),
              'email': 'Gabrielle@163.com',
              'first_name': 'Gabrielle',
              'last_name': 'Mills',
              'no': '27',
              'phone': '539.363.8103',
              'state': 'Hawaii',
              'zipcode': '53740'},
             {'birthday': datetime.date(1922, 7, 13),
              'email': 'pmorgan@zamora.biz',
              'first_name': 'Susan',
              'last_name': 'Murray',
              'no': '28',
              'phone': '001-168-553-2408x5468',
              'state': 'New Mexico',
              'zipcode': '58692'},
             {'birthday': datetime.date(1937, 11, 2),
              'email': 'ianderson@ponce-ashley.com',
              'first_name': 'Heather',
              'last_name': 'Nichols',
              'no': '29',
              'phone': '546.640.4972x469',
              'state': 'Louisiana',
              'zipcode': '43983'},
             {'birthday': datetime.date(2008, 8, 24),
              'email': 'skerr@hughes-hurley.info',
              'first_name': 'Dale',
              'last_name': 'Alexander',
              'no': '30',
              'phone': '065-607-3747',
              'state': 'Georgia',
              'zipcode': '63646'},
             {'birthday': datetime.date(1944, 3, 15),
              'email': 'ryanwhite@green.com',
              'first_name': 'Alexandra',
              'last_name': 'Washington',
              'no': '31',
              'phone': '6387019256',
              'state': 'Maryland',
              'zipcode': '37358'},
             {'birthday': datetime.date(1927, 9, 12),
              'email': 'goldengregory@price-mercer.biz',
              'first_name': 'Scott',
              'last_name': 'Huff',
              'no': '32',
              'phone': '680-437-3240x359',
              'state': 'Nevada',
              'zipcode': '60956'},
             {'birthday': datetime.date(1908, 11, 12),
              'email': 'bethany44@hotmail.com',
              'first_name': 'Juan',
              'last_name': 'Nelson',
              'no': '33',
              'phone': '866.480.2666x873',
              'state': 'California',
              'zipcode': '49066'},
             {'birthday': datetime.date(2005, 10, 26),
              'email': 'susan06@bender.com',
              'first_name': 'Ronald',
              'last_name': 'Dunn',
              'no': '34',
              'phone': '8470672052',
              'state': 'Pennsylvania',
              'zipcode': '94843'},
             {'birthday': datetime.date(1980, 9, 18),
              'email': 'jfischer@johnson.net',
              'first_name': 'Daniel',
              'last_name': 'Johnson',
              'no': '35',
              'phone': '8948498120',
              'state': 'Louisiana',
              'zipcode': '14209'},
             {'birthday': datetime.date(1910, 9, 15),
              'email': 'Ryan@163.com',
              'first_name': 'Ryan',
              'last_name': 'Bell',
              'no': '36',
              'phone': '610-146-8790',
              'state': 'Oklahoma',
              'zipcode': '78190'},
             {'birthday': datetime.date(1905, 9, 21),
              'email': 'henrycody@jenkins-reyes.com',
              'first_name': 'Richard',
              'last_name': 'Mendoza',
              'no': '37',
              'phone': '(183)150-6668',
              'state': 'Kansas',
              'zipcode': '28116'},
             {'birthday': datetime.date(1984, 6, 30),
              'email': 'elizabethzimmerman@carrillo.info',
              'first_name': 'Jenna',
              'last_name': 'Gentry',
              'no': '38',
              'phone': '(552)654-5232x879',
              'state': 'New Jersey',
              'zipcode': '85560'},
             {'birthday': datetime.date(1917, 6, 28),
              'email': 'larry49@russo-bates.info',
              'first_name': 'Joseph',
              'last_name': 'Brown',
              'no': '39',
              'phone': '001-775-957-6298x198',
              'state': 'California',
              'zipcode': '47746'},
             {'birthday': datetime.date(1998, 4, 8),
              'email': 'taylortammy@moore-smith.com',
              'first_name': 'Clayton',
              'last_name': 'Mason',
              'no': '40',
              'phone': '463.310.3623x0144',
              'state': 'North Carolina',
              'zipcode': '76567'},
             {'birthday': datetime.date(1958, 7, 16),
              'email': 'deanedward@ryan.com',
              'first_name': 'Frank',
              'last_name': 'Mendez',
              'no': '41',
              'phone': '+1-615-504-8572x73824',
              'state': 'New York',
              'zipcode': '70216'},
             {'birthday': datetime.date(1986, 10, 19),
              'email': 'youngapril@brown-powell.net',
              'first_name': 'Tracy',
              'last_name': 'Myers',
              'no': '42',
              'phone': '099-263-8132x0644',
              'state': 'Montana',
              'zipcode': '43748'},
             {'birthday': datetime.date(1941, 3, 23),
              'email': 'yesparza@parks-campbell.net',
              'first_name': 'Debbie',
              'last_name': 'Taylor',
              'no': '43',
              'phone': '001-624-651-1181x7577',
              'state': 'Utah',
              'zipcode': '17581'},
             {'birthday': datetime.date(1991, 9, 11),
              'email': 'meyerrandall@kramer-adams.com',
              'first_name': 'Rebecca',
              'last_name': 'Vance',
              'no': '44',
              'phone': '954-652-9778x673',
              'state': 'Arizona',
              'zipcode': '51685'},
             {'birthday': datetime.date(1957, 5, 27),
              'email': 'Hannah@163.com',
              'first_name': 'Hannah',
              'last_name': 'Herrera',
              'no': '45',
              'phone': '+1-433-136-7996',
              'state': 'Florida',
              'zipcode': '53815'},
             {'birthday': datetime.date(1977, 12, 1),
              'email': 'emily46@simpson.info',
              'first_name': 'Steven',
              'last_name': 'Lewis',
              'no': '46',
              'phone': '+1-455-294-2718',
              'state': 'South Dakota',
              'zipcode': '13829'},
             {'birthday': datetime.date(1972, 4, 11),
              'email': 'michellehart@jones.com',
              'first_name': 'Jason',
              'last_name': 'Heath',
              'no': '47',
              'phone': '135.627.3995',
              'state': 'Idaho',
              'zipcode': '52072'},
             {'birthday': datetime.date(1953, 9, 5),
              'email': 'nicholasgonzalez@yahoo.com',
              'first_name': 'Marilyn',
              'last_name': 'Wright',
              'no': '48',
              'phone': '+1-729-139-9336x1077',
              'state': 'North Dakota',
              'zipcode': '13065'},
             {'birthday': datetime.date(1945, 12, 5),
              'email': 'danielanderson@navarro.info',
              'first_name': 'Catherine',
              'last_name': 'Cook',
              'no': '49',
              'phone': '9890327756',
              'state': 'Kentucky',
              'zipcode': '07018'},
             {'birthday': datetime.date(1990, 7, 3),
              'email': 'robertmedina@gonzales-sanchez.com',
              'first_name': 'Darrell',
              'last_name': 'Santos',
              'no': '50',
              'phone': '(910)257-0187x4696',
              'state': 'Michigan',
              'zipcode': '53703'},
             {'birthday': datetime.date(2007, 5, 16),
              'email': 'bobby18@gmail.com',
              'first_name': 'Randy',
              'last_name': 'Compton',
              'no': '51',
              'phone': '035-451-0975x5105',
              'state': 'New Mexico',
              'zipcode': '87034'},
             {'birthday': datetime.date(1947, 5, 6),
              'email': 'teresaabbott@king-duran.biz',
              'first_name': 'Anthony',
              'last_name': 'Hall',
              'no': '52',
              'phone': '001-140-408-4277x02472',
              'state': 'Vermont',
              'zipcode': '27689'},
             {'birthday': datetime.date(1980, 5, 7),
              'email': 'nmiles@gonzalez-mendoza.com',
              'first_name': 'Derrick',
              'last_name': 'Miles',
              'no': '53',
              'phone': '(605)455-3118x3257',
              'state': 'Nebraska',
              'zipcode': '54876'},
             {'birthday': datetime.date(1957, 2, 5),
              'email': 'Emily@163.com',
              'first_name': 'Emily',
              'last_name': 'Williams',
              'no': '54',
              'phone': '001-377-818-6597x4990',
              'state': 'Washington',
              'zipcode': '75458'},
             {'birthday': datetime.date(1966, 10, 10),
              'email': 'tommy57@johnson.biz',
              'first_name': 'Julie',
              'last_name': 'May',
              'no': '55',
              'phone': '001-075-766-2546x027',
              'state': 'Washington',
              'zipcode': '50971'},
             {'birthday': datetime.date(1941, 12, 26),
              'email': 'leabigail@carr.net',
              'first_name': 'Brandon',
              'last_name': 'Gray',
              'no': '56',
              'phone': '786-528-2982x03473',
              'state': 'Florida',
              'zipcode': '64227'},
             {'birthday': datetime.date(2011, 12, 6),
              'email': 'piercemegan@yahoo.com',
              'first_name': 'Alison',
              'last_name': 'Smith',
              'no': '57',
              'phone': '001-585-626-8166x4918',
              'state': 'Wisconsin',
              'zipcode': '86972'},
             {'birthday': datetime.date(1942, 5, 14),
              'email': 'kristywarren@reeves.com',
              'first_name': 'Christopher',
              'last_name': 'Caldwell',
              'no': '58',
              'phone': '+1-234-010-9452',
              'state': 'Tennessee',
              'zipcode': '36208'},
             {'birthday': datetime.date(1960, 10, 5),
              'email': 'tina13@bishop-cook.biz',
              'first_name': 'Bradley',
              'last_name': 'Reynolds',
              'no': '59',
              'phone': '+1-793-868-2143x73311',
              'state': 'California',
              'zipcode': '32802'},
             {'birthday': datetime.date(1907, 3, 25),
              'email': 'johnjohnson@gmail.com',
              'first_name': 'Tiffany',
              'last_name': 'Roberts',
              'no': '60',
              'phone': '(227)413-3281',
              'state': 'South Carolina',
              'zipcode': '82236'},
             {'birthday': datetime.date(1922, 5, 12),
              'email': 'jonathanclark@sullivan.biz',
              'first_name': 'Matthew',
              'last_name': 'Singh',
              'no': '61',
              'phone': '135-679-3896x5746',
              'state': 'South Carolina',
              'zipcode': '51880'},
             {'birthday': datetime.date(1951, 3, 10),
              'email': 'lindabailey@weeks-shannon.com',
              'first_name': 'Edwin',
              'last_name': 'Carroll',
              'no': '62',
              'phone': '+1-195-036-1346',
              'state': 'North Carolina',
              'zipcode': '44563'},
             {'birthday': datetime.date(1975, 8, 15),
              'email': 'Rebecca@163.com',
              'first_name': 'Rebecca',
              'last_name': 'Castro',
              'no': '63',
              'phone': '389.193.3305',
              'state': 'Texas',
              'zipcode': '56725'},
             {'birthday': datetime.date(2019, 5, 20),
              'email': 'alexander70@williams.info',
              'first_name': 'Beverly',
              'last_name': 'Ayala',
              'no': '64',
              'phone': '(656)479-7356',
              'state': 'New York',
              'zipcode': '57002'},
             {'birthday': datetime.date(1940, 1, 4),
              'email': 'andrea29@stevens.com',
              'first_name': 'Erin',
              'last_name': 'Harvey',
              'no': '65',
              'phone': '055.197.2511x2912',
              'state': 'Washington',
              'zipcode': '73074'},
             {'birthday': datetime.date(1945, 11, 5),
              'email': 'rodrigueznicole@walker.com',
              'first_name': 'Joseph',
              'last_name': 'Chen',
              'no': '66',
              'phone': '+1-647-375-1298x65142',
              'state': 'Illinois',
              'zipcode': '61620'},
             {'birthday': datetime.date(1980, 3, 4),
              'email': 'christopher08@miranda-henderson.com',
              'first_name': 'Alexander',
              'last_name': 'Yang',
              'no': '67',
              'phone': '6292794760',
              'state': 'Delaware',
              'zipcode': '04448'},
             {'birthday': datetime.date(1991, 9, 6),
              'email': 'gravesrobert@evans.com',
              'first_name': 'Lonnie',
              'last_name': 'Khan',
              'no': '68',
              'phone': '001-291-935-7545',
              'state': 'Alaska',
              'zipcode': '58819'},
             {'birthday': datetime.date(1997, 1, 31),
              'email': 'felicia48@yahoo.com',
              'first_name': 'Ronnie',
              'last_name': 'Lamb',
              'no': '69',
              'phone': '2273760937',
              'state': 'New Jersey',
              'zipcode': '54652'},
             {'birthday': datetime.date(1920, 4, 1),
              'email': 'harveycarl@perry.info',
              'first_name': 'Kimberly',
              'last_name': 'Smith',
              'no': '70',
              'phone': '876.808.1915x62147',
              'state': 'Louisiana',
              'zipcode': '35239'},
             {'birthday': datetime.date(1936, 1, 23),
              'email': 'miguel65@king.com',
              'first_name': 'Yolanda',
              'last_name': 'Myers',
              'no': '71',
              'phone': '576-188-3587x7091',
              'state': 'Virginia',
              'zipcode': '71271'},
             {'birthday': datetime.date(1967, 6, 22),
              'email': 'Nicole@163.com',
              'first_name': 'Nicole',
              'last_name': 'Jenkins',
              'no': '72',
              'phone': '+1-717-650-3807x9631',
              'state': 'Maine',
              'zipcode': '86846'},
             {'birthday': datetime.date(2011, 9, 15),
              'email': 'michael58@glover.com',
              'first_name': 'Andrew',
              'last_name': 'Reyes',
              'no': '73',
              'phone': '9453856736',
              'state': 'Delaware',
              'zipcode': '05318'},
             {'birthday': datetime.date(1986, 2, 12),
              'email': 'christophergomez@bailey-perry.com',
              'first_name': 'Kristen',
              'last_name': 'Cooper',
              'no': '74',
              'phone': '001-016-584-4810x666',
              'state': 'Oklahoma',
              'zipcode': '16857'},
             {'birthday': datetime.date(2007, 4, 16),
              'email': 'savannah06@hancock.org',
              'first_name': 'Jesse',
              'last_name': 'Morgan',
              'no': '75',
              'phone': '135-504-6390x9994',
              'state': 'Kansas',
              'zipcode': '18177'},
             {'birthday': datetime.date(2016, 9, 29),
              'email': 'jesse72@bruce-osborne.org',
              'first_name': 'Madison',
              'last_name': 'Rubio',
              'no': '76',
              'phone': '(255)694-3961',
              'state': 'Colorado',
              'zipcode': '15713'},
             {'birthday': datetime.date(2005, 1, 16),
              'email': 'jasonchavez@wilson-farrell.org',
              'first_name': 'Ashley',
              'last_name': 'Harvey',
              'no': '77',
              'phone': '001-879-523-7668x710',
              'state': 'Oklahoma',
              'zipcode': '79738'},
             {'birthday': datetime.date(1976, 7, 28),
              'email': 'mirandagarcia@weaver.biz',
              'first_name': 'Rhonda',
              'last_name': 'Lewis',
              'no': '78',
              'phone': '4277270656',
              'state': 'Montana',
              'zipcode': '30189'},
             {'birthday': datetime.date(1928, 1, 18),
              'email': 'jacksonmaria@rowe.com',
              'first_name': 'Roger',
              'last_name': 'Pope',
              'no': '79',
              'phone': '161-499-7512x9160',
              'state': 'Virginia',
              'zipcode': '93504'},
             {'birthday': datetime.date(1968, 12, 7),
              'email': 'michaelmartinez@cooper.com',
              'first_name': 'Jessica',
              'last_name': 'Murillo',
              'no': '80',
              'phone': '+1-809-723-1785x995',
              'state': 'Florida',
              'zipcode': '36421'},
             {'birthday': datetime.date(1908, 4, 27),
              'email': 'Tiffany@163.com',
              'first_name': 'Tiffany',
              'last_name': 'Jackson',
              'no': '81',
              'phone': '507-467-8499x44264',
              'state': 'Ohio',
              'zipcode': '90123'},
             {'birthday': datetime.date(1990, 7, 8),
              'email': 'destiny07@gonzalez.com',
              'first_name': 'Michael',
              'last_name': 'Sanford',
              'no': '82',
              'phone': '388-875-3800',
              'state': 'Louisiana',
              'zipcode': '37173'},
             {'birthday': datetime.date(1932, 10, 13),
              'email': 'emercado@smith.com',
              'first_name': 'Jessica',
              'last_name': 'Welch',
              'no': '83',
              'phone': '(189)300-2088',
              'state': 'Montana',
              'zipcode': '99573'},
             {'birthday': datetime.date(1970, 3, 23),
              'email': 'chandlerdennis@davis-lambert.info',
              'first_name': 'Nancy',
              'last_name': 'Harmon',
              'no': '84',
              'phone': '(326)634-9275x62497',
              'state': 'Indiana',
              'zipcode': '55893'},
             {'birthday': datetime.date(1908, 5, 22),
              'email': 'michaelcruz@sandoval.com',
              'first_name': 'Jessica',
              'last_name': 'Castro',
              'no': '85',
              'phone': '+1-995-653-6233x061',
              'state': 'Louisiana',
              'zipcode': '84569'},
             {'birthday': datetime.date(1914, 12, 12),
              'email': 'aherrera@house.net',
              'first_name': 'Tiffany',
              'last_name': 'Rowe',
              'no': '86',
              'phone': '516.850.9939x54368',
              'state': 'Michigan',
              'zipcode': '88321'},
             {'birthday': datetime.date(2016, 7, 5),
              'email': 'mathewstroy@kelly.com',
              'first_name': 'Yolanda',
              'last_name': 'Vaughn',
              'no': '87',
              'phone': '+1-123-294-0024x879',
              'state': 'Oklahoma',
              'zipcode': '69837'},
             {'birthday': datetime.date(1949, 3, 3),
              'email': 'jonathangay@wallace-martin.net',
              'first_name': 'Andrew',
              'last_name': 'Bush',
              'no': '88',
              'phone': '+1-124-911-4749x36071',
              'state': 'Wyoming',
              'zipcode': '14473'},
             {'birthday': datetime.date(2003, 9, 29),
              'email': 'oarmstrong@barber.com',
              'first_name': 'Carol',
              'last_name': 'Mcintosh',
              'no': '89',
              'phone': '001-565-541-0166x453',
              'state': 'Arkansas',
              'zipcode': '40451'},
             {'birthday': datetime.date(1990, 2, 7),
              'email': 'Jacob@163.com',
              'first_name': 'Jacob',
              'last_name': 'Roth',
              'no': '90',
              'phone': '452-183-2546',
              'state': 'Michigan',
              'zipcode': '64034'},
             {'birthday': datetime.date(1989, 6, 3),
              'email': 'lwatkins@long.com',
              'first_name': 'Mary',
              'last_name': 'Valdez',
              'no': '91',
              'phone': '407-448-9055x06402',
              'state': 'California',
              'zipcode': '64529'},
             {'birthday': datetime.date(1936, 11, 2),
              'email': 'fwolfe@elliott-gallegos.net',
              'first_name': 'Nancy',
              'last_name': 'Strong',
              'no': '92',
              'phone': '001-207-163-0505x451',
              'state': 'Michigan',
              'zipcode': '60317'},
             {'birthday': datetime.date(2017, 6, 15),
              'email': 'janetwilson@yahoo.com',
              'first_name': 'Robert',
              'last_name': 'Barton',
              'no': '93',
              'phone': '7742860398',
              'state': 'Maryland',
              'zipcode': '59626'},
             {'birthday': datetime.date(1997, 12, 10),
              'email': 'matthew94@rodriguez.net',
              'first_name': 'Sheila',
              'last_name': 'Jones',
              'no': '94',
              'phone': '4678833074',
              'state': 'Arizona',
              'zipcode': '44240'},
             {'birthday': datetime.date(1944, 9, 14),
              'email': 'jhawkins@bradshaw-taylor.com',
              'first_name': 'Kelly',
              'last_name': 'Campos',
              'no': '95',
              'phone': '+1-079-986-4569x933',
              'state': 'Kansas',
              'zipcode': '42892'},
             {'birthday': datetime.date(1903, 12, 14),
              'email': 'rita77@fleming-brown.com',
              'first_name': 'George',
              'last_name': 'Riley',
              'no': '96',
              'phone': '003.288.4493x7006',
              'state': 'Illinois',
              'zipcode': '94744'},
             {'birthday': datetime.date(1947, 6, 29),
              'email': 'jsmith@west-anderson.info',
              'first_name': 'Barbara',
              'last_name': 'Reynolds',
              'no': '97',
              'phone': '+1-264-435-0665',
              'state': 'Minnesota',
              'zipcode': '54947'},
             {'birthday': datetime.date(1976, 8, 5),
              'email': 'alisonherring@steele-oconnell.com',
              'first_name': 'Rachel',
              'last_name': 'Moreno',
              'no': '98',
              'phone': '(568)548-1832x5547',
              'state': 'Delaware',
              'zipcode': '79464'},
             {'birthday': datetime.date(1980, 10, 24),
              'email': 'Marilyn@163.com',
              'first_name': 'Marilyn',
              'last_name': 'Gonzalez',
              'no': '99',
              'phone': '+1-529-851-2509',
              'state': 'New Jersey',
              'zipcode': '36321'}]
